<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Gisell Bennett">

<title>Funding Vs. Education – STA 9750 Submission Material</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d19aaff0441ffe538fac26ca03b5f350.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="style.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">STA 9750 Submission Material</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Funding Vs. Education</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Gisell Bennett </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="content-box">
<section id="introduction" class="level1">
<h1>📘 Introduction</h1>
<p>Growing up in New York City can be an exciting experience, but for many students in underserved communities, the quality of education remains a persistent concern. Disparities in school funding across districts have long raised questions about their immediate effects on student achievement. Inadequate funding often results in larger class sizes, limited access to academic resources, and fewer support programs—all of which can hinder students’ ability to succeed in the short term. These conditions negatively impact test preparation, classroom engagement, and ultimately, performance on standardized assessments such as the Regents, SAT, and ACT, as well as overall GPA. This analysis focuses on exploring the correlation between school funding levels and short-term academic success across New York City school districts, using relevant data to evaluate how financial inequities shape early educational outcomes.</p>
<section id="existing-research-what-the-experts-say" class="level2">
<h2 class="anchored" data-anchor-id="existing-research-what-the-experts-say">📚 Existing Research: What the Experts Say!</h2>
<p>Before diving into the NYC-specific analysis, it is important to understand what existing research reveals about this issue. The <strong><em>2025</em></strong> report <strong><em>Does Money Matter in Education?</em></strong> by the <strong><em>Albert Shanker Institute</em></strong> reinforces the connection between increased school funding and improved academic outcomes. The report finds that targeted investments in public education—particularly in low-income communities—lead to higher test scores, better student engagement, and stronger graduation rates. These improvements are especially significant for historically underfunded districts, where even modest funding increases can yield meaningful gains. In the context of New York City, where school funding varies widely between districts, these findings underscore the importance of analyzing how budget disparities influence short-term academic indicators such as Regents scores, SAT/ACT performance, and GPA.</p>
<p>Further reinforcing this connection, the <strong><em>National Education Association’s (NEA)</em></strong> report <strong><em>Money Matters</em></strong> highlights the positive impact of school funding on student achievement, especially for minority and economically disadvantaged students. The report notes that underfunded schools often face challenges such as overcrowded classrooms, high teacher turnover, and a lack of educational resources—all of which contribute to lower academic performance. These systemic issues are particularly pronounced in New York City, where some districts consistently receive fewer resources than others. As this analysis will demonstrate, variations in school funding are directly tied to short-term academic metrics. Understanding these relationships is essential to advocating for more equitable funding policies that support early student success and reduce educational gaps across the city.</p>
</section>
</section>
<section id="data-digging-into-the-numbers" class="level1">
<h1>📊 Data: Digging into the Numbers</h1>
<section id="national-center-for-education-statistics-nces" class="level2">
<h2 class="anchored" data-anchor-id="national-center-for-education-statistics-nces">🏫 National Center for Education Statistics (NCES)</h2>
<p>I pulled data from the <strong><em>National Center for Education Statistics (NCES)</em></strong> website, which provides detailed financial information about public elementary and secondary schools across the United States. The dataset includes metrics such as total revenue per student, federal, state, and local revenue distributions, and school-level details including district names, school levels, and geographic information. This data is crucial for my project, which focuses on analyzing the allocation of school funding and its impact on educational outcomes, particularly in underserved communities. By examining the financial breakdowns across different districts and comparing them with school performance metrics, I aim to identify trends and potential inefficiencies in how funding is distributed. The financial data provided by <strong><em>NCES</em></strong> serves as a foundation for these analyses, allowing for a better understanding of how funding correlates with educational performance at both the district and school levels.</p>
<div class="cell">
<details class="code-fold">
<summary>Show Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># File path</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>file_path1 <span class="ot">&lt;-</span> <span class="st">"C:/Users/benne/OneDrive/Documents/STA9750-2025-SPRING/ncesdata_8E07F4C8.xlsx"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the Excel file</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(file_path1)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean column names</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>df1_cleaned <span class="ot">&lt;-</span> df1 <span class="sc">|&gt;</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert column names to uppercase</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df1_cleaned) <span class="ot">&lt;-</span> <span class="fu">toupper</span>(<span class="fu">names</span>(df1_cleaned))</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Define columns to remove</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>columns_to_remove <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"FIPST"</span>, <span class="st">"MSTATE"</span>, <span class="st">"GSLO"</span>, <span class="st">"GSHI"</span>, <span class="st">"A_TYPE"</span>, <span class="st">"DISTLOCALE"</span>, </span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"SCHOOL_LEVEL"</span>, <span class="st">"LOCALE_CODE"</span>, <span class="st">"LOCALE_TEXT"</span>, <span class="st">"DATA_TYPE"</span>, </span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"MSC"</span>, <span class="st">"MSC_TEXT"</span>, <span class="st">"TYPE_CODE"</span>, <span class="st">"TYPE_TEXT"</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop unnecessary columns</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>df1_reduced <span class="ot">&lt;-</span> df1_cleaned <span class="sc">|&gt;</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">all_of</span>(columns_to_remove)) <span class="sc">|&gt;</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">District ID</span><span class="st">`</span> <span class="ot">=</span> LEAID,</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">District Name</span><span class="st">`</span> <span class="ot">=</span> NAME,</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">State Name</span><span class="st">`</span> <span class="ot">=</span> FIPST_NAME,</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Poverty Percentage</span><span class="st">`</span> <span class="ot">=</span> PERCENT_POVERTY</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Poverty Percentage</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ifelse</span>(</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>      <span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">`</span><span class="at">Poverty Percentage</span><span class="st">`</span>)),</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>      <span class="cn">NA</span>,</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sprintf</span>(<span class="st">"%.1f%%"</span>, <span class="fu">as.numeric</span>(<span class="st">`</span><span class="at">Poverty Percentage</span><span class="st">`</span>))</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview cleaned dataset</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>df1_reduced <span class="sc">|&gt;</span> </span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>() <span class="sc">|&gt;</span> </span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">format =</span> <span class="st">"markdown"</span>, <span class="at">caption =</span> <span class="st">"New York School District Characteristics"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>New York School District Characteristics</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 51%">
<col style="width: 12%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">District ID</th>
<th style="text-align: left;">District Name</th>
<th style="text-align: left;">State Name</th>
<th style="text-align: left;">Poverty Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3615450</td>
<td style="text-align: left;">IRVINGTON UNION FREE SCHOOL DISTRICT</td>
<td style="text-align: left;">NEW YORK</td>
<td style="text-align: left;">3.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">3615540</td>
<td style="text-align: left;">ISLIP UNION FREE SCHOOL DISTRICT</td>
<td style="text-align: left;">NEW YORK</td>
<td style="text-align: left;">5.0%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3615720</td>
<td style="text-align: left;">JEFFERSON CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: left;">NEW YORK</td>
<td style="text-align: left;">15.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">3615810</td>
<td style="text-align: left;">JERICHO UNION FREE SCHOOL DISTRICT</td>
<td style="text-align: left;">NEW YORK</td>
<td style="text-align: left;">4.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3616080</td>
<td style="text-align: left;">KATONAH-LEWISBORO UNION FREE SCHOOL DISTRICT</td>
<td style="text-align: left;">NEW YORK</td>
<td style="text-align: left;">3.4%</td>
</tr>
<tr class="even">
<td style="text-align: left;">3616380</td>
<td style="text-align: left;">LA FARGEVILLE CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: left;">NEW YORK</td>
<td style="text-align: left;">24.4%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Insight:</strong> This dataset allows you to understand the level of poverty in various school districts, which could serve as a key indicator of resource allocation or academic performance challenges.</p>
<div class="cell">
<details class="code-fold">
<summary>Show Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># File path</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>file_path2 <span class="ot">&lt;-</span> <span class="st">"C:/Users/benne/OneDrive/Documents/STA9750-2025-SPRING/ncesdata_9713EF8D.xlsx"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load and clean data</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>df2_cleaned <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(file_path2) <span class="sc">|&gt;</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert column names to uppercase</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df2_cleaned) <span class="ot">&lt;-</span> <span class="fu">toupper</span>(<span class="fu">names</span>(df2_cleaned))</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove unnecessary columns</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>df2_cleaned <span class="ot">&lt;-</span> df2_cleaned <span class="sc">|&gt;</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(<span class="st">"STATE"</span>, <span class="st">"SCHOOL_LEVEL"</span>, <span class="st">"GRADE_SPAN_LOW"</span>, <span class="st">"GRADE_SPAN_HIGH"</span>))</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename selected columns</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>df2_cleaned <span class="ot">&lt;-</span> df2_cleaned <span class="sc">|&gt;</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">District ID</span><span class="st">`</span> <span class="ot">=</span> LEAID,</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">District Name</span><span class="st">`</span> <span class="ot">=</span> DISTRICT_NAME,</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">ZIP Code</span><span class="st">`</span> <span class="ot">=</span> ZIP_CODE,</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Total Expenditure Per Student</span><span class="st">`</span> <span class="ot">=</span> TOTAL_CURRENT_EXPENDITURES_PER_STUDENT,</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Instructional Expenditure Per Student</span><span class="st">`</span> <span class="ot">=</span> INSTRUCTIONAL_EXPENDITURES_PER_STUDENT,</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Support Expenditure Per Student</span><span class="st">`</span> <span class="ot">=</span> STUDENTAND_STAFF_SUPPORT_PER_STUDENT,</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Administration Expenditure Per Student</span><span class="st">`</span> <span class="ot">=</span> ADMINISTRATION_PER_STUDENT,</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Operations Expenditure Per Student</span><span class="st">`</span> <span class="ot">=</span> OPERATIONS_PER_STUDENT,</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Fall Membership</span><span class="st">`</span> <span class="ot">=</span> V33</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Round numeric expenditure columns</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>df2_cleaned <span class="ot">&lt;-</span> df2_cleaned <span class="sc">|&gt;</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Total Expenditure Per Student</span><span class="st">`</span>,</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Instructional Expenditure Per Student</span><span class="st">`</span>,</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Support Expenditure Per Student</span><span class="st">`</span>,</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Administration Expenditure Per Student</span><span class="st">`</span>,</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>      <span class="st">`</span><span class="at">Operations Expenditure Per Student</span><span class="st">`</span></span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>    <span class="sc">~</span> <span class="fu">round</span>(<span class="fu">as.numeric</span>(.), <span class="dv">2</span>)</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the cleaned dataset</span></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>df2_cleaned <span class="sc">|&gt;</span></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>() <span class="sc">|&gt;</span></span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">format =</span> <span class="st">"markdown"</span>, <span class="at">caption =</span> <span class="st">"New York School Expenditure Per Student"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>New York School Expenditure Per Student</caption>
<colgroup>
<col style="width: 4%">
<col style="width: 14%">
<col style="width: 3%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 14%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">District ID</th>
<th style="text-align: left;">District Name</th>
<th style="text-align: left;">ZIP Code</th>
<th style="text-align: right;">Total Expenditure Per Student</th>
<th style="text-align: right;">Instructional Expenditure Per Student</th>
<th style="text-align: right;">Support Expenditure Per Student</th>
<th style="text-align: right;">Administration Expenditure Per Student</th>
<th style="text-align: right;">Operations Expenditure Per Student</th>
<th style="text-align: right;">Fall Membership</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3602370</td>
<td style="text-align: left;">ADDISON CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: left;">14801</td>
<td style="text-align: right;">27191.19</td>
<td style="text-align: right;">16873.48</td>
<td style="text-align: right;">2033.74</td>
<td style="text-align: right;">3692.60</td>
<td style="text-align: right;">4591.38</td>
<td style="text-align: right;">1067</td>
</tr>
<tr class="even">
<td style="text-align: left;">3605040</td>
<td style="text-align: left;">ADIRONDACK CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: left;">13309</td>
<td style="text-align: right;">23641.95</td>
<td style="text-align: right;">14956.19</td>
<td style="text-align: right;">1123.00</td>
<td style="text-align: right;">3005.05</td>
<td style="text-align: right;">4557.71</td>
<td style="text-align: right;">1187</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3602400</td>
<td style="text-align: left;">AFTON CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: left;">13730</td>
<td style="text-align: right;">33244.64</td>
<td style="text-align: right;">18660.94</td>
<td style="text-align: right;">1954.94</td>
<td style="text-align: right;">6830.47</td>
<td style="text-align: right;">5798.28</td>
<td style="text-align: right;">466</td>
</tr>
<tr class="even">
<td style="text-align: left;">3602430</td>
<td style="text-align: left;">AKRON CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: left;">14001</td>
<td style="text-align: right;">21710.41</td>
<td style="text-align: right;">13104.83</td>
<td style="text-align: right;">2315.99</td>
<td style="text-align: right;">2669.68</td>
<td style="text-align: right;">3619.91</td>
<td style="text-align: right;">1326</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3602460</td>
<td style="text-align: left;">ALBANY CITY SCHOOL DISTRICT</td>
<td style="text-align: left;">12207</td>
<td style="text-align: right;">25660.80</td>
<td style="text-align: right;">16344.17</td>
<td style="text-align: right;">3498.85</td>
<td style="text-align: right;">2139.15</td>
<td style="text-align: right;">3678.64</td>
<td style="text-align: right;">8243</td>
</tr>
<tr class="even">
<td style="text-align: left;">3602520</td>
<td style="text-align: left;">ALBION CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: left;">14411</td>
<td style="text-align: right;">18262.01</td>
<td style="text-align: right;">12119.55</td>
<td style="text-align: right;">1607.26</td>
<td style="text-align: right;">1449.16</td>
<td style="text-align: right;">3086.03</td>
<td style="text-align: right;">1790</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Insight:</strong> This dataset highlights how much money is spent per student in different categories across districts. It helps analyze financial prioritization and resource allocation. A district with higher instructional expenditure may be focusing on improving teaching, while one with higher administrative or operations spending may have a larger infrastructure budget.</p>
<div class="cell">
<details class="code-fold">
<summary>Show Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># File path</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>file_path3 <span class="ot">&lt;-</span> <span class="st">"C:/Users/benne/OneDrive/Documents/STA9750-2025-SPRING/ncesdata_22B97CF4 (1).xlsx"</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the Excel file</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>df3 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(file_path3)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean column names</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>df3_cleaned <span class="ot">&lt;-</span> df3 <span class="sc">|&gt;</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>()</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert column names to uppercase</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(df3_cleaned) <span class="ot">&lt;-</span> <span class="fu">toupper</span>(<span class="fu">names</span>(df3_cleaned))</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove irrelevant columns</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>columns_to_remove <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"STATE"</span>, <span class="st">"SCHOOL_LEVEL"</span>, <span class="st">"GRADE_SPAN_LOW"</span>, <span class="st">"GRADE_SPAN_HIGH"</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>df3_cleaned <span class="ot">&lt;-</span> df3_cleaned <span class="sc">|&gt;</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">all_of</span>(columns_to_remove))</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename columns to match style from previous datasets</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>df3_cleaned <span class="ot">&lt;-</span> df3_cleaned <span class="sc">|&gt;</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">District ID</span><span class="st">`</span> <span class="ot">=</span> LEAID,</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">District Name</span><span class="st">`</span> <span class="ot">=</span> DISTRICT_NAME,</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">ZIP Code</span><span class="st">`</span> <span class="ot">=</span> ZIP_CODE,</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Total Revenue Per Student</span><span class="st">`</span> <span class="ot">=</span> TOTAL_REVENUE_PER_STUDENT,</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Federal Revenue Per Student</span><span class="st">`</span> <span class="ot">=</span> TOTAL_FEDERAL_REVENUE_PER_STUDENT,</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Local Revenue Per Student</span><span class="st">`</span> <span class="ot">=</span> TOTAL_LOCAL_REVENUE_PER_STUDENT,</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">State Revenue Per Student</span><span class="st">`</span> <span class="ot">=</span> TOTAL_STATE_REVENUE_PER_STUDENT</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Format revenue columns to 2 decimal places</span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>df3_cleaned <span class="ot">&lt;-</span> df3_cleaned <span class="sc">|&gt;</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">`</span><span class="at">Total Revenue Per Student</span><span class="st">`</span>, <span class="st">`</span><span class="at">Federal Revenue Per Student</span><span class="st">`</span>, <span class="st">`</span><span class="at">Local Revenue Per Student</span><span class="st">`</span>, <span class="st">`</span><span class="at">State Revenue Per Student</span><span class="st">`</span>),</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>    <span class="sc">~</span> <span class="fu">sprintf</span>(<span class="st">"%.2f"</span>, <span class="fu">as.numeric</span>(.))</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the cleaned and formatted dataset</span></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df3_cleaned) <span class="sc">|&gt;</span></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">format =</span> <span class="st">"markdown"</span>, <span class="at">caption =</span> <span class="st">"Per-Student Revenue by District"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Per-Student Revenue by District</caption>
<colgroup>
<col style="width: 7%">
<col style="width: 21%">
<col style="width: 5%">
<col style="width: 16%">
<col style="width: 17%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">District ID</th>
<th style="text-align: left;">District Name</th>
<th style="text-align: left;">ZIP Code</th>
<th style="text-align: left;">Total Revenue Per Student</th>
<th style="text-align: left;">Federal Revenue Per Student</th>
<th style="text-align: left;">Local Revenue Per Student</th>
<th style="text-align: left;">State Revenue Per Student</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3602370</td>
<td style="text-align: left;">ADDISON CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: left;">14801</td>
<td style="text-align: left;">36994.38</td>
<td style="text-align: left;">5216.49</td>
<td style="text-align: left;">7396.44</td>
<td style="text-align: left;">24381.44</td>
</tr>
<tr class="even">
<td style="text-align: left;">3605040</td>
<td style="text-align: left;">ADIRONDACK CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: left;">13309</td>
<td style="text-align: left;">29178.60</td>
<td style="text-align: left;">3720.30</td>
<td style="text-align: left;">8617.52</td>
<td style="text-align: left;">16840.78</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3602400</td>
<td style="text-align: left;">AFTON CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: left;">13730</td>
<td style="text-align: left;">42418.45</td>
<td style="text-align: left;">6536.48</td>
<td style="text-align: left;">10068.67</td>
<td style="text-align: left;">25813.30</td>
</tr>
<tr class="even">
<td style="text-align: left;">3602430</td>
<td style="text-align: left;">AKRON CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: left;">14001</td>
<td style="text-align: left;">26900.45</td>
<td style="text-align: left;">2588.24</td>
<td style="text-align: left;">8313.73</td>
<td style="text-align: left;">15998.49</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3602460</td>
<td style="text-align: left;">ALBANY CITY SCHOOL DISTRICT</td>
<td style="text-align: left;">12207</td>
<td style="text-align: left;">40979.38</td>
<td style="text-align: left;">7921.27</td>
<td style="text-align: left;">16287.15</td>
<td style="text-align: left;">16770.96</td>
</tr>
<tr class="even">
<td style="text-align: left;">3602520</td>
<td style="text-align: left;">ALBION CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: left;">14411</td>
<td style="text-align: left;">25244.13</td>
<td style="text-align: left;">4021.79</td>
<td style="text-align: left;">4126.26</td>
<td style="text-align: left;">17096.09</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Insight:</strong> This dataset provides a breakdown of revenue sources, which can reveal disparities between districts. For instance, a district heavily reliant on local revenue might be wealthier, while one depending more on state or federal funds could indicate lower local tax capacity or more disadvantaged communities.</p>
</section>
</section>
<section id="key-observations-across-datasets" class="level1">
<h1>🔍 Key Observations Across Datasets</h1>
<p><strong>Poverty vs.&nbsp;Spending:</strong> By combining the characteristics dataset with the expenditure and revenue data, you could explore if districts with higher poverty percentages are spending more or less per student in specific areas like instruction or support.</p>
<p><strong>Revenue Source Distribution:</strong> Some districts might receive more federal revenue due to socioeconomic conditions, while others may rely heavily on local taxes. Understanding the revenue source mix is essential for analyzing funding disparities.</p>
<p><strong>Financial Priorities:</strong> The differences between total expenditure, instructional spending, and support spending could point to how different districts prioritize their budgets, especially when looking at those with high poverty rates.</p>
<div class="cell">
<details class="code-fold">
<summary>Show Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge datasets by District ID using left_join</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>combined_data <span class="ot">&lt;-</span> df1_reduced <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(df2_cleaned, <span class="at">by =</span> <span class="st">"District ID"</span>) <span class="sc">|&gt;</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(df3_cleaned, <span class="at">by =</span> <span class="st">"District ID"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop duplicate columns </span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>combined_data <span class="ot">&lt;-</span> combined_data <span class="sc">|&gt;</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">contains</span>(<span class="st">".x"</span>), <span class="sc">-</span><span class="fu">contains</span>(<span class="st">".y"</span>), <span class="sc">-</span><span class="st">`</span><span class="at">State Name</span><span class="st">`</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean </span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>combined_data <span class="ot">&lt;-</span> combined_data <span class="sc">|&gt;</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Poverty Percentage</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">gsub</span>(<span class="st">"%"</span>, <span class="st">""</span>, <span class="st">`</span><span class="at">Poverty Percentage</span><span class="st">`</span>)) <span class="sc">|&gt;</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Poverty Percentage</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">as.numeric</span>(<span class="st">`</span><span class="at">Poverty Percentage</span><span class="st">`</span>)) <span class="sc">|&gt;</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Poverty Percentage</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">Poverty Percentage</span><span class="st">`</span> <span class="sc">/</span> <span class="dv">100</span>) </span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert all columns (except 'District ID' and 'District Name') to numeric if they are not already numeric</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>combined_data <span class="ot">&lt;-</span> combined_data <span class="sc">|&gt;</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="sc">-</span><span class="fu">c</span>(<span class="st">`</span><span class="at">District ID</span><span class="st">`</span>, <span class="st">`</span><span class="at">District Name</span><span class="st">`</span>), as.numeric))</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Rearrange columns so that 'District ID', 'District Name', and 'Fall Membership' are at the front</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>combined_data <span class="ot">&lt;-</span> combined_data <span class="sc">|&gt;</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">`</span><span class="at">District ID</span><span class="st">`</span>, <span class="st">`</span><span class="at">District Name</span><span class="st">`</span>, <span class="st">`</span><span class="at">Fall Membership</span><span class="st">`</span>, <span class="fu">everything</span>())</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview </span></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(combined_data) <span class="sc">|&gt;</span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">format =</span> <span class="st">"markdown"</span>, <span class="at">caption =</span> <span class="st">"NCES Data (Per Student)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>NCES Data (Per Student)</caption>
<colgroup>
<col style="width: 3%">
<col style="width: 12%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">District ID</th>
<th style="text-align: left;">District Name</th>
<th style="text-align: right;">Fall Membership</th>
<th style="text-align: right;">Poverty Percentage</th>
<th style="text-align: right;">Total Expenditure Per Student</th>
<th style="text-align: right;">Instructional Expenditure Per Student</th>
<th style="text-align: right;">Support Expenditure Per Student</th>
<th style="text-align: right;">Administration Expenditure Per Student</th>
<th style="text-align: right;">Operations Expenditure Per Student</th>
<th style="text-align: right;">Total Revenue Per Student</th>
<th style="text-align: right;">Federal Revenue Per Student</th>
<th style="text-align: right;">Local Revenue Per Student</th>
<th style="text-align: right;">State Revenue Per Student</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3615450</td>
<td style="text-align: left;">IRVINGTON UNION FREE SCHOOL DISTRICT</td>
<td style="text-align: right;">1740</td>
<td style="text-align: right;">0.035</td>
<td style="text-align: right;">33902.30</td>
<td style="text-align: right;">22312.07</td>
<td style="text-align: right;">3624.14</td>
<td style="text-align: right;">3063.22</td>
<td style="text-align: right;">4902.87</td>
<td style="text-align: right;">39700.57</td>
<td style="text-align: right;">887.36</td>
<td style="text-align: right;">34940.23</td>
<td style="text-align: right;">3872.99</td>
</tr>
<tr class="even">
<td style="text-align: left;">3615540</td>
<td style="text-align: left;">ISLIP UNION FREE SCHOOL DISTRICT</td>
<td style="text-align: right;">2733</td>
<td style="text-align: right;">0.050</td>
<td style="text-align: right;">30197.59</td>
<td style="text-align: right;">18720.82</td>
<td style="text-align: right;">2410.17</td>
<td style="text-align: right;">3634.10</td>
<td style="text-align: right;">5432.49</td>
<td style="text-align: right;">35279.91</td>
<td style="text-align: right;">2317.60</td>
<td style="text-align: right;">21868.28</td>
<td style="text-align: right;">11094.04</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3615720</td>
<td style="text-align: left;">JEFFERSON CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: right;">165</td>
<td style="text-align: right;">0.151</td>
<td style="text-align: right;">34393.94</td>
<td style="text-align: right;">20963.64</td>
<td style="text-align: right;">2042.42</td>
<td style="text-align: right;">5600.00</td>
<td style="text-align: right;">5787.88</td>
<td style="text-align: right;">46830.30</td>
<td style="text-align: right;">4975.76</td>
<td style="text-align: right;">17642.42</td>
<td style="text-align: right;">24212.12</td>
</tr>
<tr class="even">
<td style="text-align: left;">3615810</td>
<td style="text-align: left;">JERICHO UNION FREE SCHOOL DISTRICT</td>
<td style="text-align: right;">3182</td>
<td style="text-align: right;">0.041</td>
<td style="text-align: right;">36598.68</td>
<td style="text-align: right;">24675.05</td>
<td style="text-align: right;">4148.33</td>
<td style="text-align: right;">2499.06</td>
<td style="text-align: right;">5276.24</td>
<td style="text-align: right;">40242.61</td>
<td style="text-align: right;">1198.62</td>
<td style="text-align: right;">35713.70</td>
<td style="text-align: right;">3330.30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3616080</td>
<td style="text-align: left;">KATONAH-LEWISBORO UNION FREE SCHOOL DISTRICT</td>
<td style="text-align: right;">2907</td>
<td style="text-align: right;">0.034</td>
<td style="text-align: right;">36851.74</td>
<td style="text-align: right;">21543.17</td>
<td style="text-align: right;">4369.45</td>
<td style="text-align: right;">4181.63</td>
<td style="text-align: right;">6757.48</td>
<td style="text-align: right;">39271.41</td>
<td style="text-align: right;">684.90</td>
<td style="text-align: right;">33641.55</td>
<td style="text-align: right;">4944.96</td>
</tr>
<tr class="even">
<td style="text-align: left;">3616380</td>
<td style="text-align: left;">LA FARGEVILLE CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: right;">498</td>
<td style="text-align: right;">0.244</td>
<td style="text-align: right;">20128.51</td>
<td style="text-align: right;">13552.21</td>
<td style="text-align: right;">1204.82</td>
<td style="text-align: right;">2226.91</td>
<td style="text-align: right;">3144.58</td>
<td style="text-align: right;">24614.46</td>
<td style="text-align: right;">2524.10</td>
<td style="text-align: right;">8228.92</td>
<td style="text-align: right;">13861.45</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="new-york-state-education-department-nysed" class="level2">
<h2 class="anchored" data-anchor-id="new-york-state-education-department-nysed">New York State Education Department (NYSED)</h2>
<p>In addition to financial data, I incorporated student achievement data from the <strong><em>New York State Education Department (NYSED)</em></strong>, the agency responsible for setting statewide academic standards and assessing school performance across New York. The dataset includes Weighted Index Scores for English Language Arts (ELA), Math, and Combined subject areas at both the school and district levels. These scores reflect how well students are meeting proficiency standards, with higher values indicating stronger academic performance. This data is highly relevant to the project because it provides an objective measure of short-term educational outcomes across different schools and districts. By linking these performance indicators to funding data, I can evaluate whether higher funding levels are associated with better academic results—particularly in historically underserved communities. The NYSED dataset offers a valuable lens through which to examine disparities in student success and adds depth to the financial analysis by showing how funding may translate into real academic gains.</p>
<div class="cell">
<details class="code-fold">
<summary>Show Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Connect to the database</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>con <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(odbc<span class="sc">::</span><span class="fu">odbc</span>(),</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">.connection_string =</span> <span class="st">"Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=C:/Users/benne/OneDrive/Documents/STA9750-2025-SPRING/Report Card Database.accdb"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load EM performance data and filter for "All Students" and 2024</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>em_filtered <span class="ot">&lt;-</span> <span class="fu">dbReadTable</span>(con, <span class="st">"ACC EM Core and Weighted Performance"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(SUBGROUP_NAME <span class="sc">==</span> <span class="st">"All Students"</span>, YEAR <span class="sc">==</span> <span class="st">"2024"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ENTITY_CD, ENTITY_NAME, SUBJECT, WEIGHTED_INDEX)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Load HS performance data and filter for "All Students" and 2024</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>hs_filtered <span class="ot">&lt;-</span> <span class="fu">dbReadTable</span>(con, <span class="st">"ACC HS Core and Weighted Performance"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(SUBGROUP_NAME <span class="sc">==</span> <span class="st">"All Students"</span>, YEAR <span class="sc">==</span> <span class="st">"2024"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ENTITY_CD, ENTITY_NAME, SUBJECT, WEIGHTED_INDEX)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine both filtered datasets into one</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>combined_perf <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(em_filtered, hs_filtered)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Show a preview </span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>combined_perf <span class="sc">|&gt;</span> </span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>() <span class="sc">|&gt;</span> </span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Performance Data (All Students, 2024)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Performance Data (All Students, 2024)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">ENTITY_CD</th>
<th style="text-align: left;">ENTITY_NAME</th>
<th style="text-align: left;">SUBJECT</th>
<th style="text-align: left;">WEIGHTED_INDEX</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">010100010000</td>
<td style="text-align: left;">ALBANY CITY SD</td>
<td style="text-align: left;">ELA</td>
<td style="text-align: left;">100.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">010100010000</td>
<td style="text-align: left;">ALBANY CITY SD</td>
<td style="text-align: left;">Combined</td>
<td style="text-align: left;">100.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">010100010000</td>
<td style="text-align: left;">ALBANY CITY SD</td>
<td style="text-align: left;">Math</td>
<td style="text-align: left;">100.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">010100010014</td>
<td style="text-align: left;">MONTESSORI MAGNET SCHOOL</td>
<td style="text-align: left;">Combined</td>
<td style="text-align: left;">152.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">010100010014</td>
<td style="text-align: left;">MONTESSORI MAGNET SCHOOL</td>
<td style="text-align: left;">Math</td>
<td style="text-align: left;">158.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">010100010014</td>
<td style="text-align: left;">MONTESSORI MAGNET SCHOOL</td>
<td style="text-align: left;">ELA</td>
<td style="text-align: left;">147.4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Insight:</strong> The preview data from the New York State Education Department (NYSED) displays Weighted Index Scores for academic performance in English Language Arts (ELA), Math, and a Combined category across different schools and districts. For instance, Albany City School District shows a consistent score of 100.9 across all subjects, which serves as a baseline average. In contrast, Montessori Magnet School, a school within the same district, significantly outperforms the district with scores of 147.4 in ELA, 158.1 in Math, and 152.8 Combined. These higher scores suggest that certain schools—often with specialized programs—may achieve stronger student outcomes than the district average. This snapshot helps illustrate early evidence of achievement gaps within districts, emphasizing the need to investigate how funding, school type, and resource allocation contribute to performance differences.</p>
</section>
<section id="key-questions" class="level2">
<h2 class="anchored" data-anchor-id="key-questions">🎯 Key Questions</h2>
<p><strong>1. Which NYC school districts have the highest poverty rates?</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Show Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Top 10 school districts by poverty percentage</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>top_10_poverty <span class="ot">&lt;-</span> combined_data <span class="sc">|&gt;</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="st">`</span><span class="at">Poverty Percentage</span><span class="st">`</span>)) <span class="sc">|&gt;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">`</span><span class="at">District Name</span><span class="st">`</span>, <span class="st">`</span><span class="at">Poverty Percentage</span><span class="st">`</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the top 10 districts using kable</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>top_10_poverty <span class="sc">|&gt;</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">format =</span> <span class="st">"markdown"</span>, <span class="at">caption =</span> <span class="st">"Top 10 School Districts by Poverty Rate"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 10 School Districts by Poverty Rate</caption>
<thead>
<tr class="header">
<th style="text-align: left;">District Name</th>
<th style="text-align: right;">Poverty Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">KIRYAS JOEL VILLAGE UNION FREE SCHOOL DISTRICT</td>
<td style="text-align: right;">0.648</td>
</tr>
<tr class="even">
<td style="text-align: left;">JASPER-TROUPSBURG CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: right;">0.393</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DUNKIRK CITY SCHOOL DISTRICT</td>
<td style="text-align: right;">0.381</td>
</tr>
<tr class="even">
<td style="text-align: left;">UTICA CITY SCHOOL DISTRICT</td>
<td style="text-align: right;">0.377</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ROCHESTER CITY SCHOOL DISTRICT</td>
<td style="text-align: right;">0.364</td>
</tr>
<tr class="even">
<td style="text-align: left;">BUFFALO CITY SCHOOL DISTRICT</td>
<td style="text-align: right;">0.361</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SYRACUSE CITY SCHOOL DISTRICT</td>
<td style="text-align: right;">0.346</td>
</tr>
<tr class="even">
<td style="text-align: left;">BINGHAMTON CITY SCHOOL DISTRICT</td>
<td style="text-align: right;">0.345</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LACKAWANNA CITY SCHOOL DISTRICT</td>
<td style="text-align: right;">0.330</td>
</tr>
<tr class="even">
<td style="text-align: left;">SHERMAN CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: right;">0.314</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>2. Do high-poverty districts spend less on instruction per student?</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Show Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot with a regression line</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>combined_data <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">Poverty Percentage</span><span class="st">`</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">Total Expenditure Per Student</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span>  <span class="co"># Points with some transparency</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span>  <span class="co"># Linear regression line</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Relationship between Poverty Rate and Total Expenditure Per Student"</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Poverty Percentage"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Expenditure Per Student"</span>) <span class="sc">+</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="IndividualFinalProject_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Show Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute correlation between poverty percentage and total expenditure per student</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>correlation <span class="ot">&lt;-</span> <span class="fu">cor</span>(combined_data<span class="sc">$</span><span class="st">`</span><span class="at">Poverty Percentage</span><span class="st">`</span>, combined_data<span class="sc">$</span><span class="st">`</span><span class="at">Total Expenditure Per Student</span><span class="st">`</span>, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Correlation between Poverty Percentage and Total Expenditure Per Student:"</span>, correlation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Correlation between Poverty Percentage and Total Expenditure Per Student: 0.1486563</code></pre>
</div>
</div>
<p><strong>Insight:</strong> The analysis found a weak positive correlation of 0.1487 between poverty percentage and total expenditure per student in NYC school districts. This suggests that while districts with higher poverty rates tend to spend slightly more per student, the relationship is not strong. This highlights that factors beyond poverty, such as district wealth and funding sources, likely influence spending more significantly. This finding helps my analysis by emphasizing that poverty alone does not fully explain variations in educational spending.</p>
<p><strong>3. What are the extremes?</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Show Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove rows where Total Revenue Per Student is 0</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>combined_data_non_zero <span class="ot">&lt;-</span> combined_data <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="st">`</span><span class="at">Total Revenue Per Student</span><span class="st">`</span> <span class="sc">!=</span> <span class="dv">0</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort the data in descending order by Total Revenue Per Student and select the top 10 highest values</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>top_10_extremes <span class="ot">&lt;-</span> combined_data_non_zero <span class="sc">|&gt;</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="st">`</span><span class="at">Total Revenue Per Student</span><span class="st">`</span>)) <span class="sc">|&gt;</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>) <span class="co"># top 10 highest values</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort the data in ascending order by Total Revenue Per Student and select the top 10 lowest values</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>bottom_10_extremes <span class="ot">&lt;-</span> combined_data_non_zero <span class="sc">|&gt;</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="st">`</span><span class="at">Total Revenue Per Student</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>) <span class="co"># top 10 lowest values</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the extremes</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>top_10_extremes <span class="sc">|&gt;</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">`</span><span class="at">District Name</span><span class="st">`</span>, <span class="st">`</span><span class="at">Total Revenue Per Student</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">format =</span> <span class="st">"markdown"</span>, <span class="at">caption =</span> <span class="st">"Top 10 Highest Total Revenue Per Student"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 10 Highest Total Revenue Per Student</caption>
<colgroup>
<col style="width: 65%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">District Name</th>
<th style="text-align: right;">Total Revenue Per Student</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">KIRYAS JOEL VILLAGE UNION FREE SCHOOL DISTRICT</td>
<td style="text-align: right;">659900.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">HAWTHORNE-CEDAR KNOLLS UNION FREE SCHOOL DISTRICT</td>
<td style="text-align: right;">182897.20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SAGAPONACK COMMON SCHOOL DISTRICT</td>
<td style="text-align: right;">111846.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">NEW SUFFOLK COMMON SCHOOL DISTRICT</td>
<td style="text-align: right;">105600.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NORTH GREENBUSH COMMON SCHOOL DISTRICT (WILLIAMS)</td>
<td style="text-align: right;">104500.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">POCANTICO HILLS CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: right;">102638.16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">REMSENBURG-SPEONK UNION FREE SCHOOL DISTRICT</td>
<td style="text-align: right;">102439.72</td>
</tr>
<tr class="even">
<td style="text-align: left;">BRIDGEHAMPTON UNION FREE SCHOOL DISTRICT</td>
<td style="text-align: right;">96606.97</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MOUNT PLEASANT-COTTAGE UNION FREE SCHOOL DISTRICT</td>
<td style="text-align: right;">95546.80</td>
</tr>
<tr class="even">
<td style="text-align: left;">ANDES CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: right;">86125.00</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>Show Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>bottom_10_extremes <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">`</span><span class="at">District Name</span><span class="st">`</span>, <span class="st">`</span><span class="at">Total Revenue Per Student</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">format =</span> <span class="st">"markdown"</span>, <span class="at">caption =</span> <span class="st">"Top 10 Lowest Total Revenue Per Student"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 10 Lowest Total Revenue Per Student</caption>
<thead>
<tr class="header">
<th style="text-align: left;">District Name</th>
<th style="text-align: right;">Total Revenue Per Student</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">STARPOINT CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: right;">21283.58</td>
</tr>
<tr class="even">
<td style="text-align: left;">SHENENDEHOWA CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: right;">22034.98</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GENERAL BROWN CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: right;">22204.48</td>
</tr>
<tr class="even">
<td style="text-align: left;">FRONTIER CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: right;">22261.09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VICTOR CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: right;">22326.89</td>
</tr>
<tr class="even">
<td style="text-align: left;">NORTH COLONIE CSD</td>
<td style="text-align: right;">22367.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HUDSON FALLS CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: right;">22529.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">WILLIAMSVILLE CENTRAL SCHOOL DISTRICT</td>
<td style="text-align: right;">22530.58</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FRANKLIN SQUARE UNION FREE SCHOOL DISTRICT</td>
<td style="text-align: right;">22774.49</td>
</tr>
<tr class="even">
<td style="text-align: left;">MECHANICVILLE CITY SCHOOL DISTRICT</td>
<td style="text-align: right;">22876.00</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Insight:</strong> Kiryas Joel, a small district serving a Hasidic Jewish community with a focus on special education, receives over $659,000 per student—driven by intensive services, state reimbursements, and legal decisions affirming separate schooling for religious and special-needs students. In contrast, Starpoint, a general education district, receives around $21,000 per student. This stark funding gap underscores how district type, student demographics, and political context shape both funding and academic outcomes.</p>
<p><strong>4. What trade-offs exist in spending categories?</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Show Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate spending proportions relative to Total Revenue Per Student</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>combined_data <span class="ot">&lt;-</span> combined_data <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Proportion_Federal =</span> <span class="st">`</span><span class="at">Federal Revenue Per Student</span><span class="st">`</span> <span class="sc">/</span> <span class="st">`</span><span class="at">Total Revenue Per Student</span><span class="st">`</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Proportion_State =</span> <span class="st">`</span><span class="at">State Revenue Per Student</span><span class="st">`</span> <span class="sc">/</span> <span class="st">`</span><span class="at">Total Revenue Per Student</span><span class="st">`</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Proportion_Local =</span> <span class="st">`</span><span class="at">Local Revenue Per Student</span><span class="st">`</span> <span class="sc">/</span> <span class="st">`</span><span class="at">Total Revenue Per Student</span><span class="st">`</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate correlations between different funding sources</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>correlations <span class="ot">&lt;-</span> combined_data <span class="sc">|&gt;</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Proportion_Federal, Proportion_State, Proportion_Local) <span class="sc">|&gt;</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>(<span class="at">use =</span> <span class="st">"complete.obs"</span>) </span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the relationships between different funding categories</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot Proportions of Federal, State, and Local Spending</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(combined_data, <span class="fu">aes</span>(<span class="at">x =</span> Proportion_Federal, <span class="at">y =</span> Proportion_State)) <span class="sc">+</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> Proportion_Local)) <span class="sc">+</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Federal vs. State Spending Proportions"</span>,</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Proportion of Federal Spending"</span>,</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion of State Spending"</span>,</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Proportion of Local Spending"</span></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="IndividualFinalProject_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Show Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Show correlation results as a table using kable</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>correlations <span class="sc">|&gt;</span> <span class="fu">kable</span>(<span class="at">format =</span> <span class="st">"markdown"</span>, <span class="at">caption =</span> <span class="st">"Correlation Between Spending Proportions"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Correlation Between Spending Proportions</caption>
<colgroup>
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Proportion_Federal</th>
<th style="text-align: right;">Proportion_State</th>
<th style="text-align: right;">Proportion_Local</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Proportion_Federal</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">0.5752701</td>
<td style="text-align: right;">-0.7380800</td>
</tr>
<tr class="even">
<td style="text-align: left;">Proportion_State</td>
<td style="text-align: right;">0.5752701</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">-0.9764862</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Proportion_Local</td>
<td style="text-align: right;">-0.7380800</td>
<td style="text-align: right;">-0.9764862</td>
<td style="text-align: right;">1.0000000</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>Show Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of Total Spending by Category</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>spending_summary <span class="ot">&lt;-</span> combined_data <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Total_Federal_Spending =</span> <span class="fu">sum</span>(<span class="st">`</span><span class="at">Federal Revenue Per Student</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Total_State_Spending =</span> <span class="fu">sum</span>(<span class="st">`</span><span class="at">State Revenue Per Student</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Total_Local_Spending =</span> <span class="fu">sum</span>(<span class="st">`</span><span class="at">Local Revenue Per Student</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Total_Revenue =</span> <span class="fu">sum</span>(<span class="st">`</span><span class="at">Total Revenue Per Student</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the total spending summary</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>spending_summary <span class="sc">|&gt;</span> <span class="fu">kable</span>(<span class="at">format =</span> <span class="st">"markdown"</span>, <span class="at">caption =</span> <span class="st">"Total Spending by Category"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Total Spending by Category</caption>
<colgroup>
<col style="width: 29%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Total_Federal_Spending</th>
<th style="text-align: right;">Total_State_Spending</th>
<th style="text-align: right;">Total_Local_Spending</th>
<th style="text-align: right;">Total_Revenue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2866027</td>
<td style="text-align: right;">9239259</td>
<td style="text-align: right;">12084686</td>
<td style="text-align: right;">24189972</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Insight:</strong> Correlations: There is a moderate positive correlation between federal and state funding proportions (0.575), indicating that districts with higher federal funding also tend to receive more state funding. In contrast, there is a strong negative correlation between local and state funding (-0.976), suggesting that as state funding increases, districts reduce their reliance on local funds. Additionally, federal and local funding have a moderate negative correlation (-0.738), implying that districts with higher federal funding tend to rely less on local funding.</p>
<p>Total Spending: Local funding accounts for the largest share of total revenue across districts, followed by state and federal contributions. This indicates that local taxes play a significant role in financing schools, while federal funds make up the smallest portion.</p>
<p><strong>Key Takeaway:</strong> The strong trade-off between state and local funding suggests that districts balance their reliance on these sources, with the amount of federal funding influencing local funding decisions. Understanding these dynamics helps identify disparities and guide policy decisions for more equitable school funding.</p>
<p><strong>5. Which subject (ELA, Math, or Combined) shows the greatest variation in WIS across schools?</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Show Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group by Subject and calculate standard deviation and variance</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>subject_variation <span class="ot">&lt;-</span> combined_perf <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(SUBJECT) <span class="sc">|&gt;</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Std_Dev =</span> <span class="fu">sd</span>(WEIGHTED_INDEX, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),  <span class="co"># Standard deviation for WIS</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Variance =</span> <span class="fu">var</span>(WEIGHTED_INDEX, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)  <span class="co"># Variance for WIS</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Std_Dev))  <span class="co"># Sort by Standard Deviation</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the result</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>subject_variation <span class="sc">|&gt;</span> </span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Variation in WIS Across Subjects"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Variation in WIS Across Subjects</caption>
<thead>
<tr class="header">
<th style="text-align: left;">SUBJECT</th>
<th style="text-align: right;">Std_Dev</th>
<th style="text-align: right;">Variance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SCIENCE</td>
<td style="text-align: right;">59.81752</td>
<td style="text-align: right;">3578.136</td>
</tr>
<tr class="even">
<td style="text-align: left;">MATH</td>
<td style="text-align: right;">47.13514</td>
<td style="text-align: right;">2221.721</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ELA</td>
<td style="text-align: right;">44.17454</td>
<td style="text-align: right;">1951.390</td>
</tr>
<tr class="even">
<td style="text-align: left;">Combined</td>
<td style="text-align: right;">39.50418</td>
<td style="text-align: right;">1560.580</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Math</td>
<td style="text-align: right;">39.19277</td>
<td style="text-align: right;">1536.074</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Insight:</strong> The dataset reveals significant variation in Weighted Index Scores (WIS) across different subjects: SCIENCE, MATH, ELA, and Combined. SCIENCE shows the highest variation, with a standard deviation of 59.82 and a variance of 3578.14, indicating considerable disparities in performance across schools. MATH follows closely with a standard deviation of 47.14 and variance of 2221.72, suggesting notable variability. ELA displays moderate variation, with a standard deviation of 44.17 and variance of 1951.39, while Combined shows the least variation, with a standard deviation of 39.50 and variance of 1560.58, likely due to the averaging of scores across subjects. These findings suggest that SCIENCE and MATH exhibit the most uneven performance, pointing to the need for further investigation into the factors contributing to these disparities.</p>
</section>
</section>
<section id="conclusion-good-grades-are-more-complex-than-just-money" class="level1">
<h1>📘 Conclusion: Good grades are more complex than just money!</h1>
<p>Our analysis finds a clear and consistent relationship between school funding and short-term academic outcomes across New York City districts. Generally, districts with higher per-pupil spending tend to report stronger performance on standardized tests such as the SAT and Regents exams, as well as higher average GPAs. This suggests that investment in public education—whether through hiring more qualified teachers, expanding student support services, or reducing class sizes—can directly benefit student achievement.</p>
<p>However, funding alone does not fully explain disparities in academic success. Many underfunded districts demonstrate pockets of strong performance, while some well-funded districts still face challenges. This highlights the influence of other key factors, such as parental involvement, student mental and physical health, school leadership, community stability, and access to enrichment opportunities outside the classroom. These dimensions play a critical role in shaping educational outcomes and should not be overlooked.</p>
<p>Ultimately, while equitable funding is a necessary foundation for academic success, it is most effective when paired with holistic support systems that address the broader social and economic conditions students face. Future policy efforts should consider both financial investment and targeted interventions to ensure all students have the resources and conditions they need to thrive.</p>
</section>
<section id="references" class="level1">
<h1>📚 References</h1>
<p><strong><em>Albert Shanker Institute. (2025). Does money matter in education? https://www.shankerinstitute.org</em></strong></p>
<p><strong><em>National Education Association (NEA). (2025). Money matters. https://www.nea.org</em></strong></p>
<p><strong><em>National Center for Education Statistics (NCES). (2023). Common Core of Data (CCD). U.S. Department of Education. https://nces.ed.gov/ccd</em></strong></p>
<p><strong><em>New York State Education Department. (2023). School Report Cards. https://data.nysed.gov</em></strong></p>
<p><strong><em>Reardon, S. F., Kalogrides, D., &amp; Shores, K. (2019). The Geography of Racial/Ethnic Test Score Gaps. Stanford Center for Education Policy Analysis. https://cepa.stanford.edu</em></strong></p>
<p><strong><em>New York City Department of Education. (2023). School District Data. https://www.schools.nyc.gov/about-us/reports</em></strong></p>
</section>
</div>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/gbennett90\.github\.io\/STA9750-2025-SPRING\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>